### ISSUE TITLE
Problem running ng serve. Error: Invalid configuration object.

### ISSUE THREAD

**Issue by danielcrisp** [klaascuvelier/ng2-i18n#1]
Hi, I just read your blog post (very helpful, thank you) and wanted to try out the code example but I'm unable to run `ng serve` or `ng build`

I cloned the repo, ran `npm i` and then `ng serve` but I get the following errors:

    Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

![image](https://cloud.githubusercontent.com/assets/1104814/18949592/000ec232-8634-11e6-85c4-30dad8066bb9.png)

Any ideas?

**Comment by klaascuvelier** [comment]
Sorry I missed this one.
There was an issue with the new Webpack that was bundled with a certain Angular-cli release.
Downgrading webpack in your project folder is the solution: https://github.com/angular/angular-cli/issues/2234#issuecomment-248174857

I would have assumed that was already fixed. Are you running the latests versions?

**Comment by danielcrisp** [comment]
Ok thanks, that did the trick - I had 2.1.0-beta.25 installed because the package.json has `^` in the version number. Removing that and reinstalling works.
